[supervisord]
nodaemon=true
user=user
logfile=/var/log/nginx/supervisord.log
pidfile=/run/supervisord.pid

[program:ttyd]
command=ttyd -p 7681 -i 127.0.0.1 -W -t fontSize=15 -t 'theme={"background":"#11071f"}' bash -lc "cd /home/user/app && /home/user/welcome.sh && exec bash"
autorestart=true
stdout_logfile=/var/log/nginx/ttyd.log
stderr_logfile=/var/log/nginx/ttyd.err.log

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/nginx/nginx.out.log
stderr_logfile=/var/log/nginx/nginx.err.log
