import path from "path"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

const LIBRARY_OUT = path.resolve(__dirname, "public/library")

export default defineConfig({
  plugins: [
    react(),
    // The /library static catalog is generated by `npm run library:build`
    // (scripts/sync-library.mjs) and lives under public/library/.
    // Vite picks it up automatically because anything in /public is served
    // at the site root, including /library/*.
    //
    // The deployable landing page (index.html) for the catalog is also
    // generated there, so a request to /library/ returns the no-JS HTML
    // version of the catalog. The React route /library (handled by the
    // LibraryApp component) returns the rich interactive view.
  ],
  base: "./",
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    outDir: "dist-web",
    sourcemap: true,
    // The static library catalog at public/library/ is auto-copied by Vite
    rollupOptions: {
      output: {
        // Avoid hash-based asset names breaking the deterministic /library/*.json
        // paths that the sync script wrote.
        assetFileNames: "assets/[name][extname]",
        chunkFileNames: "assets/[name].js",
        entryFileNames: "assets/[name].js",
      },
    },
  },
  server: {
    fs: {
      // Allow Vite to read from the workspace library package
      allow: [path.resolve(__dirname), LIBRARY_OUT],
    },
  },
  // Public dir already contains /library from `npm run library:build`
  publicDir: "public",
})
