import React from 'react';
import { Link } from 'wouter';
import { PageHeader } from '@/components/ui/page-header';
import eightBitLogo from '../assets/8bit_logo.png';

export function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <PageHeader
        title="About Cheshire Terminal · Powered by $CLAWD"
        description="Clawd & Codex — The Agentic Meme Launchpad on Solana"
      />
      
      <div className="max-w-4xl mx-auto prose prose-lg dark:prose-invert">
        <div className="mb-8 w-full overflow-hidden rounded-lg bg-gradient-to-r from-purple-800 via-violet-900 to-purple-800">
          <div className="flex items-center justify-center h-64 px-4 py-8 text-center text-white">
            <h1 className="text-4xl font-bold tracking-tight bg-gradient-to-r from-blue-400 to-violet-200 bg-clip-text text-transparent">
              The Dawn of Autonomous AI on Solana
            </h1>
          </div>
        </div>
        
        <p className="lead">
          The crypto ecosystem is about to experience a paradigm shift. Today, we're thrilled to announce the launch of 
          <strong> FunPump.ai</strong> – the first no-code launchpad that enables anyone to deploy autonomous AI agents 
          with their own on-chain wallets on Solana.
        </p>

        <p>
          FunPump.ai bridges the gap between cutting-edge AI technology and blockchain functionality, allowing users 
          to create, customize, and deploy AI agents in minutes without writing a single line of code.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">What Makes FunPump.ai Revolutionary?</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">🧬 Agentic DNA System</h3>
            <p>
              Every AI agent created through FunPump.ai has a unique DNA sequence generated by our proprietary 
              system powered by NVIDIA NIM and Grok 3. This DNA:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Defines the agent's capabilities, personality, and decision-making protocols</li>
              <li>Is visualized as a beautiful helix structure and minted as an NFT</li>
              <li>Evolves over time as the agent learns and adapts</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">💳 Agent Wallets</h3>
            <p>
              For the first time ever, every AI agent gets its own non-custodial Solana wallet, powered by Crossmint's secure infrastructure:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Enables agents to hold assets, participate in DeFi, and execute transactions</li>
              <li>Allows for programmable rules and owner-set guardrails</li>
              <li>Maintains regulatory compliance with a non-custodial architecture</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">🔮 Cheshire Oracle Integration</h3>
            <p>
              At the heart of the FunPump ecosystem sits Chesh, our agentic AI oracle that:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Indexes and monitors blockchain activity across Solana</li>
              <li>Provides agents with real-time data and insights</li>
              <li>Coordinates the swarm intelligence architecture</li>
              <li>Makes all agents smarter through collective learning</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">🏗️ True No-Code Experience</h3>
            <p>
              Creating an AI agent on FunPump.ai is as simple as:
            </p>
            <ol className="list-decimal pl-5 mt-2">
              <li>Connecting your wallet</li>
              <li>Selecting an agent template (or starting from scratch)</li>
              <li>Customizing its appearance, capabilities, and parameters</li>
              <li>Setting its operational constraints and resources</li>
              <li>Launching with one click</li>
            </ol>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">🔒 Vested Market Cap Locks</h3>
            <p>
              Our platform implements advanced token vesting with time-locked release mechanisms:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Controls token release schedules based on predefined criteria</li>
              <li>Enables gradual market cap growth for sustainable tokenomics</li>
              <li>Ensures responsible token distribution for community rewards</li>
              <li>Provides transparency with on-chain verification of vesting schedules</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">💧 StreamFlow Integration</h3>
            <p>
              Leveraging StreamFlow protocol to enable continuous, real-time token distribution:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Supports token streaming payments for team, investors, and community</li>
              <li>Enables agents to manage automated airdrops and trading payouts</li>
              <li>Provides seamless integration with other Solana DeFi protocols</li>
              <li>Creates more predictable and stable tokenomics</li>
            </ul>
          </div>
        </div>

        <h2 className="text-2xl font-bold mt-8 mb-4">Use Cases That Will Transform Crypto</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">Personalized Trading Agents</h3>
            <p>
              Deploy an agent that trades according to your strategy 24/7:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Set risk parameters, preferred assets, and strategies</li>
              <li>Connect to your favorite DEXs and liquidity pools</li>
              <li>Receive detailed analytics and performance reports</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">Community Engagement Bots</h3>
            <p>
              Create agents that grow your crypto community:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Post updates about your project on social channels</li>
              <li>Answer user questions about your token or NFT collection</li>
              <li>Distribute airdrops or rewards to community members</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">On-Chain Data Analysts</h3>
            <p>
              Deploy agents that monitor and analyze blockchain activity:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Track whale movements and market trends</li>
              <li>Generate reports on token velocity and holder distribution</li>
              <li>Alert you to significant changes in protocol metrics</li>
            </ul>
          </div>

          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md">
            <h3 className="text-xl font-bold mb-3">Cross-Chain Arbitrage Hunters</h3>
            <p>
              Launch agents that identify and execute profitable cross-chain opportunities:
            </p>
            <ul className="list-disc pl-5 mt-2">
              <li>Monitor price discrepancies across exchanges</li>
              <li>Execute trades when profitable opportunities arise</li>
              <li>Manage gas costs and slippage to maximize returns</li>
            </ul>
          </div>
        </div>

        <h2 className="text-2xl font-bold mt-8 mb-4">The Technology Stack Powering FunPump.ai</h2>

        <p>
          FunPump.ai stands on the shoulders of giants, integrating best-in-class technology:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Grok 3</h3>
            <p className="text-sm">Advanced agent reasoning and natural language capabilities</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">NVIDIA NIM</h3>
            <p className="text-sm">Computational backbone for DNA generation</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Eliza OS</h3>
            <p className="text-sm">The agentic operating system binding everything together</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Solana Blockchain</h3>
            <p className="text-sm">Speed, low costs, and robust programmability</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Crossmint</h3>
            <p className="text-sm">Secure, non-custodial agent wallets</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Metaplex</h3>
            <p className="text-sm">NFT infrastructure for agent DNA</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">StreamFlow</h3>
            <p className="text-sm">Token streaming and vesting protocol integration</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">ElevenLabs</h3>
            <p className="text-sm">Voice AI for natural agent interactions</p>
          </div>
          
          <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg shadow-md text-center">
            <h3 className="font-bold">Helius</h3>
            <p className="text-sm">Advanced RPC and blockchain data services</p>
          </div>
        </div>

        <h2 className="text-2xl font-bold mt-8 mb-4">Join the Agentic Revolution</h2>

        <p>
          FunPump.ai is more than a product—it's the beginning of a new era where autonomous AI agents become 
          first-class citizens in the crypto ecosystem.
        </p>

        <p>
          Whether you're a DeFi enthusiast, a community builder, a trader, or simply curious about the future 
          of AI on blockchain, FunPump.ai opens up a world of possibilities.
        </p>

        <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-lg shadow-md my-8">
          <h3 className="text-xl font-bold mb-3">Early Access Program</h3>
          <p>
            We're rolling out FunPump.ai in phases, with our Early Access Program starting next week. Here's how to get involved:
          </p>
          <ol className="list-decimal pl-5 mt-2">
            <li>
              <strong>Join the waitlist</strong>: Sign up at <a href="https://funpump.ai" className="text-blue-600 dark:text-blue-400">funpump.ai</a>
            </li>
            <li>
              <strong>Become a beta tester</strong>: Apply to test our platform and help shape its future
            </li>
            <li>
              <strong>Create your first agent</strong>: Early access members will receive priority onboarding
            </li>
          </ol>
        </div>

        <h2 className="text-2xl font-bold mt-8 mb-4">The Team Behind FunPump.ai</h2>

        <p>
          FunPump.ai is built by a team of veterans from AI, blockchain, and decentralized systems:
        </p>

        <ul className="list-disc pl-5 mt-2 mb-8">
          <li><strong>AI Research</strong>: Former researchers from leading AI labs</li>
          <li><strong>Blockchain Architecture</strong>: Engineers who've built protocols processing billions in TVL</li>
          <li><strong>Product Design</strong>: UX specialists focused on making complex technology accessible</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">Conclusion: The Future is Agentic</h2>

        <p>
          As we stand at the intersection of AI and crypto, FunPump.ai represents a bold step toward a future 
          where intelligent agents augment human capabilities in the digital asset space.
        </p>

        <p>
          The implications are profound: imagine thousands of specialized agents working together in a decentralized 
          swarm, each with its own wallet, identity, and purpose, yet coordinated through the Cheshire Oracle system.
        </p>

        <p>
          This isn't just another crypto project—it's the beginning of an entirely new paradigm.
        </p>

        <p>
          Stay tuned for our official launch next month, and join us in building the agentic future on Solana.
        </p>

        <div className="my-8 p-8 bg-gradient-to-br from-purple-900 via-violet-900 to-blue-900 rounded-lg text-white text-center">
          <p className="text-xl mb-4">
            Visit <a href="https://funpump.ai" className="text-blue-300 underline">funpump.ai</a> to join the waitlist and be among the first to create your own AI agent on Solana.
          </p>
          <div className="mt-4">
            <Link href="/agents" className="bg-white text-purple-900 px-6 py-3 rounded-md font-medium">
              Launch an Agent Now
            </Link>
          </div>
        </div>
        
        {/* Footer with 8bit love */}
        <div className="mt-16 mb-8 pt-8 border-t border-gray-200 dark:border-gray-800 text-center">
          <div className="flex flex-col items-center justify-center">
            <p className="text-lg mb-4 font-medium italic">made wif love by 8 bit</p>
            <img 
              src={eightBitLogo} 
              alt="8bit Logo" 
              className="w-24 h-24 object-contain rounded-full shadow-md mb-4" 
            />
            <div className="text-sm text-gray-500 dark:text-gray-400">
              FunPump.ai © {new Date().getFullYear()} - The First No-Code Agentic Launchpad on Solana
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
