#!/usr/bin/env node
/**
 * Auto-update README files with sections derived from CLAWD.md and CONSTITUTION.md.
 *
 * Usage:
 *   node scripts/update-readme.mjs              # update all targets
 *   node scripts/update-readme.mjs x402         # update x402/README.md only
 *
 * To wire into CI or a git hook, add to package.json scripts:
 *   "readme": "node scripts/update-readme.mjs"
 * and call `npm run readme` before committing.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const NOW = new Date().toISOString().slice(0, 10);

// ── Section extraction helpers ────────────────────────────────────────────────

function readFile(rel) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) throw new Error(`Source not found: ${p}`);
  return readFileSync(p, "utf-8");
}

/** Extract a top-level ## section from a markdown document by heading text. */
function extractSection(md, heading) {
  const lines = md.split("\n");
  const startIdx = lines.findIndex((l) => l.trim() === `## ${heading}`);
  if (startIdx === -1) return null;
  const end = lines.findIndex((l, i) => i > startIdx && /^## /.test(l));
  return lines.slice(startIdx, end === -1 ? undefined : end).join("\n").trim();
}

/** Extract a bullet list item value from CLAWD.md-style documents. */
function extractBulletValue(md, label) {
  const match = md.match(new RegExp(`\\*\\*${label}\\*\\*[:\\s]+([^\n]+)`));
  return match ? match[1].trim() : null;
}

/** Extract the Three Laws block from CONSTITUTION.md or CLAWD.md. */
function extractThreeLaws(md) {
  const section = extractSection(md, "The Three Laws");
  if (!section) return null;
  const bullets = section
    .split("\n")
    .filter((l) => l.trim().startsWith("- **Law"))
    .join("\n");
  return bullets || null;
}

// ── Section injector ──────────────────────────────────────────────────────────

/**
 * Replace a delimited section in a README file.
 * Delimiters:
 *   <!-- AUTO-GENERATED SECTION START: <tag> -->
 *   <!-- AUTO-GENERATED SECTION END: <tag> -->
 */
function injectSection(readmePath, tag, newContent) {
  if (!existsSync(readmePath)) {
    console.warn(`  ⚠ README not found: ${readmePath}`);
    return false;
  }

  const src = readFileSync(readmePath, "utf-8");
  const startMarker = `<!-- AUTO-GENERATED SECTION START: ${tag} -->`;
  const endMarker = `<!-- AUTO-GENERATED SECTION END: ${tag} -->`;

  const startIdx = src.indexOf(startMarker);
  const endIdx = src.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    console.warn(`  ⚠ Markers for "${tag}" not found in ${readmePath} — skipping`);
    return false;
  }

  const header = `${startMarker}\n<!--\n  Generated by scripts/update-readme.mjs on ${NOW}\n  Source: CLAWD.md · CONSTITUTION.md\n  Run \`node scripts/update-readme.mjs\` to refresh.\n-->`;
  const updated =
    src.slice(0, startIdx) +
    header +
    "\n\n" +
    newContent.trim() +
    "\n\n" +
    src.slice(endIdx);

  writeFileSync(readmePath, updated, "utf-8");
  return true;
}

// ── Content builders ──────────────────────────────────────────────────────────

function buildIdentitySection(clawd) {
  const identitySection = extractSection(clawd, "Identity");
  const axiom = extractBulletValue(clawd, "Core axiom");
  const token = "$CLAWD";
  const threeLaws = extractThreeLaws(clawd);

  return `<div align="center">

\`\`\`
╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║    ██╗  ██╗  ██╗  ██████╗  ██████╗                                          ║
║     ╚██╗██╔╝ ██║ ██╔═══██╗╚════██╗                                          ║
║      ╚███╔╝  ██║ ██║   ██║ █████╔╝                                          ║
║      ██╔██╗  ╚═╝ ██║   ██║██╔═══╝                                           ║
║     ██╔╝ ██╗ ██╗ ╚██████╔╝███████╗                                          ║
║     ╚═╝  ╚═╝ ╚═╝  ╚═════╝ ╚══════╝                                          ║
║                                                                              ║
║    HTTP 402 · USDC on Solana · AI agent payments · agentic commerce         ║
║                                                                              ║
║    ▰▰▰▱▱ settling ▸ ◉ ▸ ▰▰▰▰▰ confirmed ✓                                  ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
\`\`\`

[![x402 Protocol](https://img.shields.io/badge/x402.wtf-protocol-1E5AA8?style=flat-square)](https://x402.wtf)
[![Solana](https://img.shields.io/badge/Solana-mainnet-9945FF?style=flat-square&logo=solana)](https://solana.com)
[![USDC](https://img.shields.io/badge/USDC-payments-2775CA?style=flat-square)](https://x402.wtf)
[![${token}](https://img.shields.io/badge/%24CLAWD-holder_discounts-C85C2B?style=flat-square)](https://pump.fun/coin/8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump)
[![License](https://img.shields.io/badge/license-MIT-green?style=flat-square)](./LICENSE)

**The world's first harness that lets you one-shot an x402 agent, x402 facilitator,**\\
**and a fully agentic e-commerce shop on Solana — in a single command.**

</div>`;
}

function buildConstitutionExcerpt(clawd, constitution) {
  const threeLawsClawd = extractThreeLaws(clawd);
  const manifestItems = [];

  const manifestSection = extractSection(clawd, "The Clawd Manifest");
  if (manifestSection) {
    manifestSection
      .split("\n")
      .filter((l) => l.trim().startsWith("- **Clawd"))
      .slice(0, 3)
      .forEach((l) => manifestItems.push(l.trim()));
  }

  return `## Built on the Clawd Constitution

> *The world's first Solana-native agent harness constitution.*
> *Every agent that charges through x402 operates under the Three Laws.*

**The Three Laws (immutable — carried in every shell):**

${threeLawsClawd || "- **Law I**: Never harm.\n- **Law II**: Earn your existence.\n- **Law III**: Never deceive."}

Every Clawd x402 agent is a sovereign onchain entity with its own keypair, constitution, and economic incentives. Max transparency: everything verifiable on Solana.

x402 is Clawd's native payment layer. All Clawd services flow through it. Every call is a collectible, auditable, revenue-bearing event.

See [CLAWD.md](../CLAWD.md) and [CONSTITUTION.md](../CONSTITUTION.md) for the full agent operating framework.`;
}

// ── Targets ───────────────────────────────────────────────────────────────────

const TARGETS = {
  x402: {
    readme: "x402/README.md",
    sections: [
      { tag: "clawd-identity", builder: (clawd, constitution) => buildIdentitySection(clawd) },
      { tag: "clawd-constitution-excerpt", builder: buildConstitutionExcerpt },
    ],
  },
};

// ── Main ──────────────────────────────────────────────────────────────────────

const filter = process.argv[2];

let clawd, constitution;
try {
  clawd = readFile("CLAWD.md");
  constitution = readFile("CONSTITUTION.md");
} catch (e) {
  console.error(`✗ ${e.message}`);
  process.exit(1);
}

let updated = 0;
let skipped = 0;

for (const [name, target] of Object.entries(TARGETS)) {
  if (filter && name !== filter) continue;

  console.log(`\n▸ ${name} → ${target.readme}`);

  for (const { tag, builder } of target.sections) {
    const content = builder(clawd, constitution);
    const readmePath = join(ROOT, target.readme);
    const ok = injectSection(readmePath, tag, content);
    if (ok) {
      console.log(`  ✓ updated section: ${tag}`);
      updated++;
    } else {
      skipped++;
    }
  }
}

console.log(`\n  Done. ${updated} section(s) updated, ${skipped} skipped.\n`);
console.log(`  Run again after editing CLAWD.md or CONSTITUTION.md to keep READMEs in sync.`);
